# Generated by Django 4.0.3 on 2022-07-07 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('/^[a-zA-Z]{2,20}/')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(validators=[django.core.validators.RegexValidator(message='Password should be alphanumeric with at least one capital letter, small letter, digit & special character.', regex='/^(?=.\\d)(?=.[a-z])(?=.[A-Z])(?=.[@.#&+-])[A-Za-z0-9@.#&+-]{8,}$/')])),
                ('phone_number', models.TextField()),
                ('password_reset_token', models.TextField()),
                ('password_reset_token_generated_at', models.FloatField()),
                ('verification_token', models.TextField()),
                ('verification_token_generated_at', models.FloatField()),
                ('profile_pic', models.TextField()),
                ('cover_pic', models.TextField()),
                ('is_verified', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('created_at', models.FloatField()),
                ('updated_at', models.FloatField()),
            ],
        ),
    ]
