# Generated by Django 4.0.3 on 2022-07-08 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cover_pic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.FloatField(default=1657255939857.541),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,20}$')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Password should be alphanumeric with at least one capital letter, small letter, digit & special character.', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_reset_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password_reset_token_generated_at',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.FloatField(default=1657255939857.541),
        ),
    ]
