# Generated by Django 4.0.3 on 2022-07-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_cover_pic_alter_users_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.FloatField(default=1657255986297.827),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.FloatField(default=1657255986297.827),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='verification_token_generated_at',
            field=models.FloatField(null=True),
        ),
    ]
